### ISSUE TITLE
"Error: attempt to apply non-function" - tryCatchLog package must be attached to work

### ISSUE THREAD

**Issue by chrsigg** [aryoda/tryCatchLog#41]
Using `tryCatchLog` without attaching the package produces an error:

``` r
tryCatchLog::tryCatchLog({
 stop("stop")
})
#> Error in h(simpleError(msg, call)): attempt to apply non-function
```

This is not ideal when using `tryCatchLog` in a script, and a real problem when using it inside a package. It forces the package author to specify the dependency using `Depends:` in the `DESCRIPTION` file, which should be avoided as it modifies the search path (see http://r-pkgs.had.co.nz/namespace.html#namespace for example).

Please consider rewriting the `.onAttach` function such that your package can be used without having to attach it. 

And thank you for your work. Having access to the full stack trace inside `tryCatch` blocks is much appreciated.

**Comment by aryoda** [comment]
Thanks for reporting this issue, this must definitely work correctly and looks like a bug!

I am trying to find out what happens internally ;-)

BTW: I am using the `tryCatchLog` package in my own packages by specifying it in the
`Imports` section and this should work (at least I have never observed a problem like above).
**Edit:** I have used the prev. CRAN version (without `.onAttach`) so this does not prove anything ;-)

**Comment by aryoda** [comment]
I can reproduce the wrong behaviour and the reason is (as you have already found out) the `.onAttach` function I am using. Thanks for your help!

I will do some more testing before pushing an fixed version.

Unluckily I have published this new version at CRAN today and I guess others may be affected as well.

**At all readers: Please vote here if you are in need for a fixed version at CRAN soon (since I don't want to "flood" the CRAN volunteers with CRAN submissions until it is really necessary).**

**Comment by AndreMikulec** [comment]
One Vote is for: "to have the fixed CRAN version soon"

aryoda,
Thanks for the excellent package.

I have not tried  the function" error."  But the same happens on simple "message"

Attachment or "not attached" does not matter.

I have not tried "stop".
The error (for me) happens on the simple "message" function.

I wrap 100+ functions with *tryCatchLog::tryCatchLog*
in my in-development tradeModel package:
```
https://github.com/AndreMikulec/tradeModel/tree/feature/in_development
```

I will try to help a little. . . .
Simple.
```r
foo1 <- function(Symbol = NULL) {
  message(stringr::str_c("Begin - ", Symbol))
}
# foo1(Symbol = "IBM")
```
```
> foo1(Symbol = "IBM")
Begin - IBM
```
Simple OK.
Wrapper.
```
foo2 <- function(Symbol = NULL) {
  tryCatchLog::tryCatchLog({
  message(stringr::str_c("Begin - ", Symbol))
})}
# foo2(Symbol = "IBM")
```
```
> foo2(Symbol = "IBM")
Error in .tryCatchLog.env$info.log.func(log.msg) : 
  attempt to apply non-function
```
So the wrapper is not O.K.
Goes into here ...
```
withRestarts({
    signalCondition(cond)
    defaultHandler(cond)
  }, muffleMessage = function() NULL)
```
With condition
```
cond
message(stringr::str_c("Begin - ", Symbol))
```
Try without any wrapper and no message function.
```
foo3 <- function(Symbol = NULL) {
  message("Begin - ")
}
# foo3(Symbol = "IBM")
```
```
Begin -
```
so that works.
Test if tidyverse is the problem.
```
foo4 <- function(Symbol = NULL) {
  tryCatchLog::tryCatchLog({
  message(base::paste0("Begin - ", Symbol))
})}
# foo4(Symbol = "IBM")
```
```
> foo4(Symbol = "IBM")
Error in .tryCatchLog.env$info.log.func(log.msg) : 
  attempt to apply non-function
```
So, the tidyverse is not the problem.
Try if the :: function is the problem.
```
foo5 <- function(Symbol = NULL) {
  tryCatchLog::tryCatchLog({
  message(paste0("Begin - ", Symbol))
})}
# foo5(Symbol = "IBM")
```
The :: function is not the problem.

In the meanwhile, I will "try" to revert to the older version of package tryCatchLog.
Thanks,
Andre

**Comment by AndreMikulec** [comment]
I tested many github versions all the way back to Jun 2, 2018.
No old github install worked.
https://github.com/aryoda/tryCatchLog/commit/6626fface1b2fedeaf197655aeee60a75717f0b4

The previous cran release does work.:
https://cran.r-project.org/bin/windows/contrib/3.4/tryCatchLog_1.0.2.zip

**Comment by aryoda** [comment]
@AndreMikulec Thanks for your support :-)

I have just pushed a new release candidate that should fix the problems.

As @chrsigg has indicated using `.onAttach` was a stupid idea of mine :-(
Now I am initializing everything in the `.onLoad` hook and using `.onAttach` only to spit out a message depending on the initialized internal state.

Can you please test the new github version by installing it via

```
# install.packages("devtools")
library(devtools)
install_github("aryoda/tryCatchLog")
```

and give me a feed back here?

THX a lot!

**Edit 1:** I guess I have introduce the problem at github with 03c62939 (2018-06-01)...

**Comment by AndreMikulec** [comment]
@aryoda ,

Thanks, it seems to work again:

```r
> devtools::install_github("aryoda/tryCatchLog")

> futile.logger::flog.threshold("ERROR")
NULL
> (function() { tryCatchLog::tryCatchLog({ message(paste0("Hello")) }) })()
Hello

> devtools::session_info()
 tryCatchLog      1.1.3   2019-03-22 [1] Github (aryoda/tryCatchLog@3effccb)
 
> (function() { tryCatchLog::tryCatchLog({ stop(paste0("Hello")) }) })()
ERROR [2019-03-22 14:09:26] [ERROR] Hello

Compact call stack:
. . . etc . . .
```

**Comment by chrsigg** [comment]
I tested 3effccb9 with the built in logger (that is, without `futile`) from a script and from inside a package. It works in both cases wiiiithout having to attach the package. Thank you for the quick response.

**Comment by aryoda** [comment]
The fixed version is now published at CRAN: https://cran.r-project.org/package=tryCatchLog
